name: treasure_hunt
description: An Online Treasure Hunt.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  fluttertoast: ^8.2.4
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.0
  routemaster: ^1.0.1
  shared_preferences: ^2.2.2
  flutter_barcode_scanner: ^2.0.0
  vibration: ^1.8.3
  intl: ^0.18.1
  flutter_highlight: ^0.7.0
  simple_animation_progress_bar: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/playfair_display/PlayFairDisplay-Regular.ttf
        - asset: assets/fonts/playfair_display/PlayFairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/playfair_display/PlayFairDisplay-Bold.ttf
          weight: 700
